// Generated by scripts/generate_contracts.py; do not edit.
export const recommendationStatuses = ["solved", "confirmation_required", "blocked_unverified_rule", "no_safe_solution", "invalid_state"] as const;
export type RecommendationStatus = typeof recommendationStatuses[number];
export const spells = ["indecision", "reflection", "repulsion", "attraction"] as const;
export type Spell = typeof spells[number];
