from __future__ import annotations

import argparse
import csv
import hashlib
import json
from collections import Counter
from pathlib import Path
from typing import Any

import cv2
import numpy as np

from refine_arena_boundary import (
    refine_boundary_documents,
    render_refinement_assets,
)

SCHEMA_VERSION = "0.9.0"
ARENA_ID = "grougalorasalar-arena-canonical-0.9.0"
REFERENCE_WIDTH = 1951
REFERENCE_HEIGHT = 1267
ORIGIN = np.array([964.895, 441.7425], dtype=np.float64)
BASIS_X = np.array([66.75, 33.375], dtype=np.float64)
BASIS_Y = np.array([-66.75, 33.375], dtype=np.float64)
DIRECTIONS = {
    "negative_x": (-1, 0),
    "positive_x": (1, 0),
    "negative_y": (0, -1),
    "positive_y": (0, 1),
}
ALLOWED_AUTHORITIES = {
    "visible_empty_map",
    "visible_combat_screenshot",
    "user_boundary_annotation",
    "user_hidden_cell_annotation",
    "geometric_inference",
    "parity_inference",
    "unresolved",
}


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def dump_json(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def project(x: float, y: float) -> tuple[float, float]:
    point = ORIGIN + x * BASIS_X + y * BASIS_Y
    return round(float(point[0]), 6), round(float(point[1]), 6)


def polygon_for_cell(x: int, y: int) -> list[dict[str, float]]:
    # Logical square corners become the four visible isometric diamond corners.
    corners = [
        (x - 0.5, y - 0.5),
        (x + 0.5, y - 0.5),
        (x + 0.5, y + 0.5),
        (x - 0.5, y + 0.5),
    ]
    return [{"x": px, "y": py} for px, py in (project(cx, cy) for cx, cy in corners)]


def source_authority(old_class: str) -> tuple[str, float, str, list[str]]:
    if old_class in {"walkableConfirmed", "walkableObserved"}:
        return "visible_empty_map", 1.0, "none", [
            "empty-arena-raster",
            "combat-screenshot-cross-check",
        ]
    if old_class == "boundaryUnverified":
        return "user_boundary_annotation", 1.0, "partial_edge", [
            "user-green-boundary-centre-rule",
            "empty-arena-raster",
            "grid-continuation",
            "parity-cross-check",
        ]
    if old_class == "occludedUnknown":
        return "user_hidden_cell_annotation", 1.0, "architecture_or_foreground", [
            "user-hidden-cell-overlay",
            "grid-continuation",
            "parity-cross-check",
            "combat-screenshot-cross-check",
        ]
    raise ValueError(f"Unsupported old class: {old_class}")


def build_cells(project_root: Path) -> tuple[dict[str, Any], dict[str, Any], dict[str, Any]]:
    old = load_json(project_root / "data" / "arena" / "arena-model.draft-v0.5.0.json")
    old_class_by_cell: dict[tuple[int, int], str] = {}
    for class_name, items in old["cellSets"].items():
        if class_name == "permanentBlocked":
            continue
        for item in items:
            key = (int(item["x"]), int(item["y"]))
            if key in old_class_by_cell:
                raise ValueError(f"Duplicate draft cell {key}")
            old_class_by_cell[key] = class_name

    # The exact canonical footprint is the user-confirmed fixed arena envelope.
    # It can also be generated by the four integer inequalities below.
    generated = {
        (x, y)
        for x in range(-12, 14)
        for y in range(-12, 14)
        if -11 <= x + y <= 13 and -13 <= x - y <= 13
    }
    if generated != set(old_class_by_cell):
        missing = sorted(generated - set(old_class_by_cell))
        extra = sorted(set(old_class_by_cell) - generated)
        raise ValueError(f"Draft/envelope mismatch: missing={missing}, extra={extra}")

    ordered = sorted(generated, key=lambda item: (item[1], item[0]))
    id_by_cell = {cell: index for index, cell in enumerate(ordered)}
    cells: list[dict[str, Any]] = []
    for index, (x, y) in enumerate(ordered):
        old_class = old_class_by_cell[(x, y)]
        authority, confidence, occlusion, provenance = source_authority(old_class)
        neighbours = []
        for direction, (dx, dy) in DIRECTIONS.items():
            neighbour = (x + dx, y + dy)
            if neighbour in generated:
                neighbours.append(
                    {
                        "direction": direction,
                        "id": id_by_cell[neighbour],
                        "x": neighbour[0],
                        "y": neighbour[1],
                    }
                )
        boundary = len(neighbours) < 4
        cx, cy = project(x, y)
        cells.append(
            {
                "id": index,
                "stableId": f"C{index:03d}",
                "x": x,
                "y": y,
                "parity": "light" if (x + y) % 2 == 0 else "dark",
                "sourceAuthority": authority,
                "confidence": confidence,
                "boundary": boundary,
                "occlusion": occlusion,
                "referencePixelCenter": {"x": cx, "y": cy},
                "referencePolygon": polygon_for_cell(x, y),
                "neighbors": neighbours,
                "provenance": provenance,
                "supersededDraftClass": old_class,
            }
        )

    by_sum = Counter(x + y for x, y in generated)
    by_diff = Counter(x - y for x, y in generated)
    direct_total = len(generated)
    sum_total = sum(by_sum.values())
    diff_total = sum(by_diff.values())
    if not direct_total == sum_total == diff_total == 338:
        raise ValueError((direct_total, sum_total, diff_total))

    # Parity invariant: all logical orthogonal neighbours must flip colour.
    parity_errors = []
    for x, y in generated:
        for dx, dy in DIRECTIONS.values():
            neighbour = (x + dx, y + dy)
            if neighbour in generated and ((x + y) & 1) == ((neighbour[0] + neighbour[1]) & 1):
                parity_errors.append(((x, y), neighbour))
    if parity_errors:
        raise ValueError(f"Parity errors: {parity_errors[:5]}")

    cells_doc = {
        "schemaVersion": SCHEMA_VERSION,
        "arenaModelId": ARENA_ID,
        "status": "canonical_user_verified_fixed_footprint",
        "sourceOfTruth": True,
        "totalCells": direct_total,
        "coordinateSystem": {
            "type": "integer_square_grid_rendered_isometrically",
            "originCell": {"x": 0, "y": 0},
            "xAxisScreenDirection": "down_right",
            "yAxisScreenDirection": "down_left",
            "referenceSize": {"width": REFERENCE_WIDTH, "height": REFERENCE_HEIGHT},
            "originPixel": {"x": float(ORIGIN[0]), "y": float(ORIGIN[1])},
            "basisX": {"x": float(BASIS_X[0]), "y": float(BASIS_X[1])},
            "basisY": {"x": float(BASIS_Y[0]), "y": float(BASIS_Y[1])},
            "projectionFormula": "pixel = origin + x*basisX + y*basisY",
            "cellPolygonFormula": "logical square [x±0.5,y±0.5] projected through the same affine basis",
        },
        "footprint": {
            "integerInequalities": [
                "-12 <= x <= 13",
                "-12 <= y <= 13",
                "-11 <= x + y <= 13",
                "-13 <= x - y <= 13",
            ],
            "holes": [],
            "permanentBlockedCells": [],
        },
        "parityRule": {
            "formula": "(x + y) mod 2",
            "zeroParity": "light",
            "oneParity": "dark",
            "neighborInvariant": "orthogonal logical neighbours always have different parity",
            "visualEvidence": {
                "source": "empty-arena-reference",
                "medianLabLZeroParity": 208.0,
                "medianLabLOneParity": 182.5,
                "medianSeparation": 25.5,
                "note": "Visible brightness is a cross-check only; logical parity is coordinate-derived.",
            },
        },
        "countVerification": {
            "directUniqueCoordinateCount": direct_total,
            "byXPlusY": {str(key): by_sum[key] for key in sorted(by_sum)},
            "byXPlusYTotal": sum_total,
            "byXMinusY": {str(key): by_diff[key] for key in sorted(by_diff)},
            "byXMinusYTotal": diff_total,
            "allMethodsAgree": True,
        },
        "sourceReferences": [
            {
                "id": "retained-combat-reference",
                "path": "assets/reference/user_reference.png",
                "role": "canonical_reference_coordinate_system",
            },
            {
                "id": "empty-arena-raster",
                "path": "assets/reference/empty_arena.jpeg",
                "role": "grid_edges_centres_parity_and_static_landmarks",
            },
            {
                "id": "user-hidden-cell-overlay",
                "path": "assets/reference/user_hidden_cells_annotation.png",
                "role": "occluded_outer_cell_confirmation",
            },
            {
                "id": "user-green-boundary-centre-rule",
                "path": None,
                "role": "outermost_marked_cell_centres_are_included",
                "retention": "conversation_evidence_applied; original byte asset unavailable in active phase runtime",
            },
            {
                "id": "phase7-real-combat-fixtures",
                "path": "packages/fixtures/real/phase7/",
                "role": "cross_screenshot_registration_and_occupancy_evidence",
            },
        ],
        "cells": cells,
    }

    # Build the exterior cycle without geometry dependencies. Shared cell edges
    # cancel; the remaining degree-2 graph is the hole-free arena boundary.
    edge_counts: dict[tuple[tuple[int, int], tuple[int, int]], int] = {}
    for x, y in generated:
        vertices = [
            (2 * x - 1, 2 * y - 1),
            (2 * x + 1, 2 * y - 1),
            (2 * x + 1, 2 * y + 1),
            (2 * x - 1, 2 * y + 1),
        ]
        for start, end in zip(vertices, vertices[1:] + vertices[:1]):
            key = tuple(sorted((start, end)))
            edge_counts[key] = edge_counts.get(key, 0) + 1
    exterior_edges = [edge for edge, count in edge_counts.items() if count == 1]
    adjacency: dict[tuple[int, int], list[tuple[int, int]]] = {}
    for start, end in exterior_edges:
        adjacency.setdefault(start, []).append(end)
        adjacency.setdefault(end, []).append(start)
    if any(len(neighbours) != 2 for neighbours in adjacency.values()):
        raise ValueError("Canonical boundary is not one closed degree-2 cycle")
    start = min(adjacency)
    cycle = [start]
    previous = None
    current = start
    while True:
        candidates = sorted(adjacency[current])
        next_vertex = candidates[0] if candidates[0] != previous else candidates[1]
        if next_vertex == start:
            cycle.append(start)
            break
        cycle.append(next_vertex)
        previous, current = current, next_vertex
        if len(cycle) > len(exterior_edges) + 1:
            raise ValueError("Boundary cycle tracing did not terminate")
    if len(cycle) != len(exterior_edges) + 1:
        raise ValueError("Boundary contains multiple cycles or a hole")
    exterior = [(x2 / 2.0, y2 / 2.0) for x2, y2 in cycle]
    boundary_cells = [cell for cell in cells if cell["boundary"]]
    boundary_edges = []
    for cell in boundary_cells:
        x, y = cell["x"], cell["y"]
        present = {(n["x"], n["y"]) for n in cell["neighbors"]}
        for direction, (dx, dy) in DIRECTIONS.items():
            if (x + dx, y + dy) not in present:
                boundary_edges.append(
                    {
                        "cellId": cell["id"],
                        "stableId": cell["stableId"],
                        "cell": {"x": x, "y": y},
                        "direction": direction,
                    }
                )
    boundary_doc = {
        "schemaVersion": SCHEMA_VERSION,
        "arenaModelId": ARENA_ID,
        "totalBoundaryCells": len(boundary_cells),
        "totalBoundaryEdges": len(boundary_edges),
        "boundaryCells": [
            {"id": cell["id"], "stableId": cell["stableId"], "x": cell["x"], "y": cell["y"]}
            for cell in boundary_cells
        ],
        "boundaryEdges": boundary_edges,
        "exteriorLogicalVertices": [
            {"x": float(x), "y": float(y)} for x, y in exterior
        ],
        "exteriorReferencePixels": [
            {"x": px, "y": py} for px, py in (project(x, y) for x, y in exterior)
        ],
        "holes": [],
    }
    edge_report = refine_boundary_documents(project_root, cells_doc, boundary_doc)
    return cells_doc, boundary_doc, edge_report


def write_csv(path: Path, cells: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            [
                "id",
                "stable_id",
                "x",
                "y",
                "parity",
                "source_authority",
                "confidence",
                "boundary",
                "occlusion",
                "reference_center_x",
                "reference_center_y",
                "neighbor_ids",
            ]
        )
        for cell in cells:
            writer.writerow(
                [
                    cell["id"],
                    cell["stableId"],
                    cell["x"],
                    cell["y"],
                    cell["parity"],
                    cell["sourceAuthority"],
                    f'{cell["confidence"]:.6f}',
                    str(cell["boundary"]).lower(),
                    cell["occlusion"],
                    f'{cell["referencePixelCenter"]["x"]:.6f}',
                    f'{cell["referencePixelCenter"]["y"]:.6f}',
                    "|".join(str(item["id"]) for item in cell["neighbors"]),
                ]
            )


def registration_document(project_root: Path) -> dict[str, Any]:
    refs = []
    for ref_id, rel_path, role, measured in [
        (
            "empty-arena",
            "assets/reference/empty_arena.jpeg",
            "clean_grid_and_parity_reference",
            {
                "referenceToImageAffine": [[0.6439939982741252, 0.000023601380444710166, 312.84912086433985], [-0.000023601380444710166, 0.6439939982741252, 18.804303567570535]],
                "originImage": {"x": 934.246136, "y": 303.261049},
                "basisXImage": {"x": 42.987387, "y": 21.491724},
                "basisYImage": {"x": -42.985812, "y": 21.494875},
                "inlierCount": 118,
                "medianResidualCell": 0.02014,
                "p95ResidualCell": 0.055749,
                "confidence": 0.888766,
            },
        ),
        (
            "user-hidden-cells",
            "assets/reference/user_hidden_cells_annotation.png",
            "user_occluded_boundary_evidence",
            {
                "referenceToImageAffine": [[0.5930517196322986, 0.000042254312188819974, 227.94263475709064], [-0.000042254312188819974, 0.5930517196322986, 11.451037149878564]],
                "originImage": {"x": 800.193939, "y": 273.386415},
                "basisXImage": {"x": 39.587613, "y": 19.790281},
                "basisYImage": {"x": -39.584792, "y": 19.795922},
                "inlierCount": 146,
                "medianResidualCell": 0.026184,
                "p95ResidualCell": 0.054083,
                "confidence": 0.903038,
            },
        ),
    ]:
        path = project_root / rel_path
        image = cv2.imread(str(path), cv2.IMREAD_COLOR)
        refs.append(
            {
                "id": ref_id,
                "path": rel_path,
                "role": role,
                "width": int(image.shape[1]) if image is not None else None,
                "height": int(image.shape[0]) if image is not None else None,
                "sha256": sha256(path) if path.exists() else None,
                "measuredRegistration": measured,
            }
        )
    return {
        "schemaVersion": SCHEMA_VERSION,
        "arenaModelId": ARENA_ID,
        "canonicalReference": {
            "path": "assets/reference/user_reference.png",
            "width": REFERENCE_WIDTH,
            "height": REFERENCE_HEIGHT,
            "origin": {"x": float(ORIGIN[0]), "y": float(ORIGIN[1])},
            "basisX": {"x": float(BASIS_X[0]), "y": float(BASIS_X[1])},
            "basisY": {"x": float(BASIS_Y[0]), "y": float(BASIS_Y[1])},
        },
        "functionContract": {
            "python": "register_screenshot_to_arena(image, project_root) -> RegistrationResult",
            "compatibilityAlias": "registerScreenshotToArena(image, project_root)",
            "steps": [
                "decode",
                "bounded_working_copy",
                "distributed_ORB_landmarks",
                "RANSAC_affine_basis",
                "project_canonical_centres",
                "measure_cell_residuals",
                "compare_alternative_hypothesis",
                "review_gate_on_ambiguity",
            ],
        },
        "acceptanceThresholds": {
            "minimumInliers": 40,
            "minimumSpatialRegions": 3,
            "automaticMedianResidualCellMax": 0.06,
            "automaticP95ResidualCellMax": 0.10,
            "reviewP95ResidualCellMax": 0.16,
        },
        "registeredEvidence": refs,
    }


def landmarks_document() -> dict[str, Any]:
    logical_landmarks = [
        ("origin", 0, 0, "grid_origin"),
        ("min_x", -12, 1, "boundary_extreme"),
        ("max_x", 13, 0, "boundary_extreme"),
        ("min_y", 1, -12, "boundary_extreme"),
        ("max_y", 0, 13, "boundary_extreme"),
        ("min_sum_left", -12, 1, "minimum_x_plus_y_diagonal"),
        ("min_sum_right", 1, -12, "minimum_x_plus_y_diagonal"),
        ("max_sum_left", 0, 13, "maximum_x_plus_y_diagonal"),
        ("max_sum_right", 13, 0, "maximum_x_plus_y_diagonal"),
        ("min_diff", -6, 7, "minimum_x_minus_y_diagonal"),
        ("max_diff", 7, -6, "maximum_x_minus_y_diagonal"),
    ]
    return {
        "schemaVersion": SCHEMA_VERSION,
        "arenaModelId": ARENA_ID,
        "logicalGridLandmarks": [
            {
                "id": landmark_id,
                "cell": {"x": x, "y": y},
                "referencePixel": {"x": project(x, y)[0], "y": project(x, y)[1]},
                "role": role,
            }
            for landmark_id, x, y, role in logical_landmarks
        ],
        "distributedStaticReferenceRegions": [
            {"id": "top_left_architecture", "referenceRect": {"x": 0, "y": 0, "width": 650, "height": 360}},
            {"id": "top_centre_temple", "referenceRect": {"x": 650, "y": 0, "width": 650, "height": 300}},
            {"id": "top_right_architecture", "referenceRect": {"x": 1300, "y": 0, "width": 651, "height": 390}},
            {"id": "left_board_edge", "referenceRect": {"x": 100, "y": 250, "width": 500, "height": 500}},
            {"id": "right_board_edge", "referenceRect": {"x": 1350, "y": 250, "width": 500, "height": 500}},
            {"id": "lower_static_tracks", "referenceRect": {"x": 250, "y": 720, "width": 1450, "height": 360}},
        ],
        "note": "Runtime registration uses distributed ORB features and grid-basis consistency; no single landmark is sufficient for acceptance.",
    }


def svg_document(cells: list[dict[str, Any]], boundary: dict[str, Any]) -> str:
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{REFERENCE_WIDTH}" height="{REFERENCE_HEIGHT}" viewBox="0 0 {REFERENCE_WIDTH} {REFERENCE_HEIGHT}">',
        '<rect width="100%" height="100%" fill="#000"/>',
        '<g id="playable-cells" fill="#fff" stroke="#777" stroke-width="0.8">',
    ]
    for cell in cells:
        points = " ".join(f'{p["x"]:.6f},{p["y"]:.6f}' for p in cell["referencePolygon"])
        parts.append(
            f'<polygon id="{cell["stableId"]}" data-cell-id="{cell["id"]}" data-x="{cell["x"]}" data-y="{cell["y"]}" data-parity="{cell["parity"]}" points="{points}"/>'
        )
    parts.append("</g>")
    exterior = " ".join(f'{p["x"]:.6f},{p["y"]:.6f}' for p in boundary["exteriorReferencePixels"])
    parts.append(f'<polyline id="arena-boundary" points="{exterior}" fill="none" stroke="#00ff00" stroke-width="3"/>')
    parts.append("</svg>\n")
    return "\n".join(parts)


def render_assets(project_root: Path, cells_doc: dict[str, Any], boundary_doc: dict[str, Any]) -> None:
    assets = project_root / "assets" / "arena"
    assets.mkdir(parents=True, exist_ok=True)
    cells = cells_doc["cells"]
    mask = np.zeros((REFERENCE_HEIGHT, REFERENCE_WIDTH), dtype=np.uint8)
    centres = np.zeros((REFERENCE_HEIGHT, REFERENCE_WIDTH, 4), dtype=np.uint8)
    polygons = np.zeros((REFERENCE_HEIGHT, REFERENCE_WIDTH, 4), dtype=np.uint8)
    boundary_image = np.zeros((REFERENCE_HEIGHT, REFERENCE_WIDTH, 4), dtype=np.uint8)
    for cell in cells:
        polygon = np.array([[round(p["x"]), round(p["y"])] for p in cell["referencePolygon"]], dtype=np.int32)
        cv2.fillPoly(mask, [polygon], 255)
        colour = (255, 255, 255, 255) if cell["parity"] == "light" else (150, 150, 150, 255)
        cv2.fillPoly(polygons, [polygon], colour)
        cv2.polylines(polygons, [polygon], True, (40, 40, 40, 255), 1, cv2.LINE_AA)
        cx = round(cell["referencePixelCenter"]["x"])
        cy = round(cell["referencePixelCenter"]["y"])
        cv2.circle(centres, (cx, cy), 3, (255, 255, 255, 255), -1, cv2.LINE_AA)
        if cell["boundary"]:
            cv2.fillPoly(boundary_image, [polygon], (0, 255, 255, 90))
            cv2.polylines(boundary_image, [polygon], True, (0, 255, 255, 255), 2, cv2.LINE_AA)
    cv2.imwrite(str(assets / "grougalorasalar-mask.png"), mask)
    cv2.imwrite(str(assets / "grougalorasalar-cell-centers.png"), centres)
    cv2.imwrite(str(assets / "grougalorasalar-cell-polygons.png"), polygons)
    cv2.imwrite(str(assets / "grougalorasalar-boundary-debug.png"), boundary_image)
    (assets / "grougalorasalar-mask.svg").write_text(
        svg_document(cells, boundary_doc), encoding="utf-8"
    )

    reference = cv2.imread(str(project_root / "assets" / "reference" / "user_reference.png"), cv2.IMREAD_COLOR)
    if reference is None:
        raise RuntimeError("Missing canonical reference image")
    overlay = reference.copy()
    for cell in cells:
        polygon = np.array([[round(p["x"]), round(p["y"])] for p in cell["referencePolygon"]], dtype=np.int32)
        colour = (0, 255, 0) if not cell["boundary"] else (0, 165, 255)
        cv2.polylines(overlay, [polygon], True, colour, 1, cv2.LINE_AA)
        cx = round(cell["referencePixelCenter"]["x"])
        cy = round(cell["referencePixelCenter"]["y"])
        cv2.circle(overlay, (cx, cy), 2, colour, -1, cv2.LINE_AA)
        cv2.putText(overlay, str(cell["id"]), (cx - 8, cy + 4), cv2.FONT_HERSHEY_SIMPLEX, 0.22, colour, 1, cv2.LINE_AA)
    cv2.imwrite(str(assets / "grougalorasalar-debug-overlay.png"), overlay)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    project_root = args.project_root.resolve()
    cells_doc, boundary_doc, edge_report = build_cells(project_root)
    expected = {
        project_root / "data" / "arena" / "grougalorasalar.cells.json": cells_doc,
        project_root / "data" / "arena" / "grougalorasalar.boundary.json": boundary_doc,
        project_root / "data" / "arena" / "grougalorasalar.registration.json": registration_document(project_root),
        project_root / "data" / "arena" / "grougalorasalar.landmarks.json": landmarks_document(),
        project_root / "VALIDATION" / "edge-review-report.json": edge_report,
    }
    if args.check:
        for path, value in expected.items():
            actual = load_json(path)
            if actual != value:
                raise SystemExit(f"Generated artefact is stale: {path}")
        print("Canonical arena JSON artefacts are reproducible.")
        return
    for path, value in expected.items():
        dump_json(path, value)
    write_csv(project_root / "data" / "arena" / "grougalorasalar.cells.csv", cells_doc["cells"])
    render_assets(project_root, cells_doc, boundary_doc)
    render_refinement_assets(project_root, cells_doc, edge_report)
    print(
        json.dumps(
            {
                "arenaModelId": ARENA_ID,
                "totalCells": cells_doc["totalCells"],
                "boundaryCells": boundary_doc["totalBoundaryCells"],
                "boundaryEdges": boundary_doc["totalBoundaryEdges"],
                "countMethodsAgree": cells_doc["countVerification"]["allMethodsAgree"],
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
