#!/usr/bin/env python3
from __future__ import annotations
import hashlib, json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMAS = sorted((ROOT / "schemas").glob("*.schema.json"))
manifest = {"schemaVersion":"0.9.0","schemas":[]}
for path in SCHEMAS:
    raw = path.read_bytes()
    data = json.loads(raw)
    manifest["schemas"].append({
        "name": path.name,
        "id": data.get("$id"),
        "sha256": hashlib.sha256(raw).hexdigest(),
    })
(ROOT / "packages/contracts/schema-manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True)+"\n")
statuses = json.loads((ROOT / "schemas/recommendation.schema.json").read_text())["properties"]["status"]["enum"]
spells = json.loads((ROOT / "schemas/legal-action.schema.json").read_text())["properties"]["spell"]["anyOf"][0]["enum"]
ts = "// Generated by scripts/generate_contracts.py; do not edit.\n"
ts += "export const recommendationStatuses = " + json.dumps(statuses) + " as const;\n"
ts += "export type RecommendationStatus = typeof recommendationStatuses[number];\n"
ts += "export const spells = " + json.dumps(spells) + " as const;\n"
ts += "export type Spell = typeof spells[number];\n"
(ROOT / "packages/contracts/src/generated.ts").write_text(ts)
print(f"generated {len(SCHEMAS)} schema manifest entries")
